import { Component } from '@angular/core';

@Component({
  selector: 'app-prasadam',
  templateUrl: './prasadam.component.html',
  styleUrls: ['./prasadam.component.scss']
})
export class PrasadamComponent {
aboutPrsadam=[
   "If you know some Hare Krishna devotees I am sure you have heard them talk about prasadam. But you may not be completely clear what prasadam actually is.",
   "The literal meaning of the Sanskrit word “prasadam” is mercy. So when we say “Krishna prasadam” we are referring to Krishna’s mercy.",
   "To understand what prasadam is we need to clear up a common misconception. Generally we are under the impression that we are the owners of the things that we posses and these things are meant for our enjoyment. And the materialistic persons are always trying to get more and more possessions and enjoy them more and more. That is the materialistic concept of life.",
   "The actual fact is that everything is provided by Krishna therefore everything belongs to Krishna. We can take the things that Krishna provides and and use these raw materials to produce something but we have to admit that we can not make anything unless Krishna provides the raw materials. And we can not transform the raw materials unless Krishna gives us the intelligence how to do this.",
   "It is something like if you employ a carpenter to build a nice bookshelf for you. You supply him the wood, you pay him for his labor, and in the end if the carpenter claims that the bookshelf belongs to him he is mistaken. It is your bookshelf because you have provided the carpenter with the raw materials and paid him for his labor.",
   "So the concept of prasadam is to recognize the fact that everything belongs to Krishna and because these things belong to Krishna they should be used for Krishna’s pleasure. Although most generally when you hear devotees talking about prasadam they are referring to foodstruffs that have been offered to Krishna, prasadam can refer to anything that we offer to Krishna. In the aroti ceremony for example many different items are offered to Krishna including incense, a ghee lame, water, a flower, etc. So all of these things also, once they have been offered to Krishna and enjoyed by Krishna, become Krishna-prasadam. So there is flower-garland prasadam, ghee-lamp prasadam, incense prasadam and of course the food prasadam that we have all probably experienced."
]
BacePrsadam=[
  "There is something wonderful about prasadam which is illustrated by this experience of Lord Sri Caitanya Mahaprabhu related in the Sri Caitanya-caritamrta Antya 16.108:",
  "Sri Caitanya Mahaprabhu said, “These ingredients, such as sugar, camphor, black pepper, cardamom, cloves, butter, spices and licorice, are all material. Everyone has tasted these material substances before. However, in these ingredients there are extraordinary tastes and uncommon fragrances. Just taste them and see the difference in the experience. Apart from the taste, even the fragrance pleases the mind and makes one forget any other sweetness besides its own.”",
  "“Therefore, it is to be understood that the spiritual nectar of Krishna’s lips has touched these ordinary ingredients and transferred to them all their spiritual qualities. A fragrance and taste that are uncommon and greatly enchanting and that make one forget all other experiences are attributes of Krishna’s lips. This prasadam has been made available only as a result of many pious activities. Now taste it with great faith and devotion.” Loudly chanting the holy name of Hari, all of them tasted the prasadam. As they tasted it, their minds became mad in the ecstasy of love.",
  "So there is some amazing transformation that takes place when something which is apparently material is offered to Krishna with love and devotion. I have experienced it also personally. Wondering where these amazing tastes come from and knowing that the prasadam was prepared from quite ordinary ingredients but experiencing truly amazing tastes…",
  "So Krishna prasadam is a wonderful thing.",
  "And why should we only eat Krishna prasadam and nothing else?",
  "Because as I tried to explain before everything belongs to Krishna therefore everything is meant for the service of Krishna, for the pleasure of Krishna, so if we take things for ourselves, for our own pleasure and try to enjoy them without first offering them to Krishna then we become thieves. If we take something that belongs to Krishna and use it for ourselves then we have stolen it from Krishna and we become sinful thieves.",
  "And there is another aspect to this, and that is karma. It is a big subject but simply put everything we do in the material world, good or bad, generates a reaction that we will have to enjoy or suffer in the future. So if we are performing these activities that generate good and bad karma that will force us to continue taking birth in the material world perpetually so that we can experience the good and bad karma we have accumulated in this life. So unless we can stop generating karma there is no escape for us from the material world.",
  "And we can not stop eating, we can not stop performing activities. So what is the answer here? The answer is that if we work for Krishna there will be no karmic reaction generated by that work and if we eat foods that have been prepared with love and devotion and offered to Krishna that eating will not generate any karmic reaction. Rather this service to Krishna and eating Krishna prasadam will stop the karmic reactions that are stored up within our hearts from acting on us. The analogy which is given is that of seeds. When we perform an activity, good or bad, that sows a seed within our heart and when that seed grows and bears fruit then we will suffer or enjoy the reaction. Like with trees some seeds grow very quickly and some take a long time to grow. So the good or bad reactions to our activities do not immediately come. They are stored up in our hearts like seeds. This service to Krishna, chanting Hare Krishna and honoring Krishna prasadam is likened to frying the seeds. If you take some seeds and fry them in oil over a high heat then even if you plant them and water them, the will not grow.",
  "So the reason that if we are serious about advancing in spiritual life that we must only eat Krishna prasadam and nothing else is that if we eat foodstuffs which are not prepared by devotees and offered to Krishna with love then we will be eating only sin and we will be subject to the karmic reactions involved in that food. It will entangle us more and more in the cycle of birth and death.",
  "So for most of us that means we have to learn how to cook for Krishna, because if we don’t cook for Krishna and offer the food to Krishna then how will we be able to get Krishna prasadam on a regular basis?",
  "I hope you are well and happy in Krishna consciousness.",
  "Chant Hare Krishna and be happy!",
  "Hari Bol !"
]
}
